version: '3.8' 

services:
  db:
    image: postgres:17
    container_name: odoo18_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=odoo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: odoo:18.0
    container_name: odoo18_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo_user
      - PASSWORD=odoo_password
      - ODOO_MASTER_PASSWD=super_secret_master_password
    volumes:
      - web_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons 
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_odoo18
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_data:
  web_data:
  pgadmin_data: